name: splitio
description: split.io official Flutter plugin.
version: 0.1.0-rc.2
homepage: https://split.io/
repository: https://github.com/splitio/flutter-sdk-plugin

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.split.splitio
        pluginClass: SplitioPlugin
      ios:
        pluginClass: SplitioPlugin
