import Foundation

enum Method: String {
    case initialize = "init"
    case client = "getClient"
    case destroy = "destroy"
    case flush = "flush"
    case clientReady = "clientReady"
    case clientReadyFromCache = "clientReadyFromCache"
    case clientUpdated = "clientUpdated"
    case clientTimeout = "clientTimeout"
    case getTreatment = "getTreatment"
    case getTreatments = "getTreatments"
    case getTreatmentWithConfig = "getTreatmentWithConfig"
    case getTreatmentsWithConfig = "getTreatmentsWithConfig"
    case getTreatmentsByFlagSet = "getTreatmentsByFlagSet"
    case getTreatmentsByFlagSets = "getTreatmentsByFlagSets"
    case getTreatmentsWithConfigByFlagSet = "getTreatmentsWithConfigByFlagSet"
    case getTreatmentsWithConfigByFlagSets = "getTreatmentsWithConfigByFlagSets"
    case track = "track"
    case getAttribute = "getAttribute"
    case getAllAttributes = "getAllAttributes"
    case setAttribute = "setAttribute"
    case setAttributes = "setAttributes"
    case removeAttribute = "removeAttribute"
    case clearAttributes = "clearAttributes"
    case splitNames = "splitNames"
    case splits = "splits"
    case split = "split"
    case impressionLog = "impressionLog"
    case getUserConsent = "getUserConsent"
    case setUserConsent = "setUserConsent"
}

enum Argument: String {
    case apiKey = "apiKey"
    case matchingKey = "matchingKey"
    case bucketingKey = "bucketingKey"
    case config = "sdkConfiguration"
    case splitName = "splitName"
    case attributes = "attributes"
    case eventType = "eventType"
    case trafficType = "trafficType"
    case value = "value"
    case properties = "properties"
    case attributeName = "attributeName"
    case flagSet = "flagSet"
    case flagSets = "flagSets"
}
